### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by mr-c** [FeddrickAquino/sse2rvv#1]
Hello, what is the license of this project?

**Comment by hasindu2008** [comment]
Oops, meant to be MIT, but had forgotten to add it. Now added :D
Are there any dev boards with RISCV processors available today with rvv - at that time we could not find one?

**Comment by mr-c** [comment]
Thanks!

I have very little experience with RISCV. I was interested from the perspective of https://github.com/simd-everywhere/simde

**Comment by mr-c** [comment]
Thanks for the license! Now that the RVV C intrinsics are nearly final, [we are getting ready to start accepting implementations of RVV for SSE and other intrinsics in SIMDe](https://github.com/simd-everywhere/simde/issues/1087).

Did you find any dev boards? I would be interested in seeing benchmarking on real hardware using the latest clang & GCC trunk versions. Comparing both `sse2rrv` and using SIMDe; perhaps the compiler's autovectorizers are quite good?

I guess the assembly could also be compared, using instruction counts as a proxy for speed.

**Comment by hasindu2008** [comment]
Came accross a few dev boards when I checked last year- for instance https://www.aliexpress.com/item/1005002856721588.html?gatewayAdapt=glo2deu. But I did not end up buying one, as I was not sure how reliable those are also I had concerns about the state of the toolchains.

**Comment by mr-c** [comment]
Yeah, according to https://doi.org/10.48550/arXiv.2210.08882 the XuanTie 910 core is RVV version 0.7.1; so I would guess that the XuanTie C906 is also not RVV 1.0;

**Comment by mr-c** [comment]
https://www.analoglamb.com/product/kendryte-k230-risc-v-development-board-canmv-k230/ claims RVV 1.0 for the 1st CPU

> CPU: core1 - 64bit, RISC-V processor, 1.6GHz, supports RISC-V Vector Extension 1.0 specification with FPU, VPU; core0 - 64bit, RISC-V processor, 800MHz, supports RISC-V 64GCB instruction set;

Discussion at https://www.reddit.com/r/RISCV/comments/17b10y6/kendryte_k230_riscv_development_board_canmvk230/

![image](https://github.com/FeddrickAquino/sse2rvv/assets/1330696/90caf250-9b10-4d6b-8f73-f4a35cd82ee4)

**Comment by hasindu2008** [comment]
Seems like it is pre-order, not sure if it is already built or not.
There are a few boards with rvv 0.7 on aliexpress when I checked some time ago, but given rvv1.0 is coming, might be better to wait.

**Comment by mr-c** [comment]
> Seems like it is pre-order, not sure if it is already built or not.

I ordered one and according to the tracker, it should leave Beijing soon 🙏

**Comment by hasindu2008** [comment]
ahh let me know if it comes, I can order one too if it is legit :D
